/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Sori_ani.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    console.log(actions);
    actions.LipAnimation.play();
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-1.15, -2.54, 0.8]}>
        <primitive object={nodes.spine003} />
        <skinnedMesh geometry={nodes.구체001.geometry} material={materials.SKIN} skeleton={nodes.구체001.skeleton} />
        <skinnedMesh
          geometry={nodes.구체001_1.geometry}
          material={materials['매테리얼.012']}
          skeleton={nodes.구체001_1.skeleton}
        />
        <skinnedMesh
          geometry={nodes.구체001_2.geometry}
          material={materials['매테리얼.022']}
          skeleton={nodes.구체001_2.skeleton}
        />
        <skinnedMesh
          geometry={nodes.구체001_3.geometry}
          material={materials['매테리얼.023']}
          skeleton={nodes.구체001_3.skeleton}
        />
        <skinnedMesh
          geometry={nodes.구체001_4.geometry}
          material={materials['매테리얼.025']}
          skeleton={nodes.구체001_4.skeleton}
        />
        <skinnedMesh
          geometry={nodes.구체001_5.geometry}
          material={materials['매테리얼.007']}
          skeleton={nodes.구체001_5.skeleton}
        />
        <skinnedMesh
          geometry={nodes.구체001_6.geometry}
          material={materials['매테리얼.001']}
          skeleton={nodes.구체001_6.skeleton}
        />
        <skinnedMesh
          geometry={nodes.구체001_7.geometry}
          material={materials['매테리얼.002']}
          skeleton={nodes.구체001_7.skeleton}
        />
        <skinnedMesh
          geometry={nodes.구체001_8.geometry}
          material={materials['매테리얼.003']}
          skeleton={nodes.구체001_8.skeleton}
        />
        <skinnedMesh
          geometry={nodes.구체001_9.geometry}
          material={materials['매테리얼.026']}
          skeleton={nodes.구체001_9.skeleton}
        />
        <skinnedMesh
          geometry={nodes.구체001_10.geometry}
          material={materials['매테리얼.027']}
          skeleton={nodes.구체001_10.skeleton}
        />
        <skinnedMesh
          geometry={nodes.구체001_11.geometry}
          material={materials['매테리얼.028']}
          skeleton={nodes.구체001_11.skeleton}
        />
        <skinnedMesh
          geometry={nodes.구체001_12.geometry}
          material={materials['매테리얼.005']}
          skeleton={nodes.구체001_12.skeleton}
        />
        <skinnedMesh
          geometry={nodes.구체001_13.geometry}
          material={materials.매테리얼}
          skeleton={nodes.구체001_13.skeleton}
        />
        <skinnedMesh
          geometry={nodes.구체001_14.geometry}
          material={materials['매테리얼.006']}
          skeleton={nodes.구체001_14.skeleton}
        />
        <skinnedMesh
          geometry={nodes.구체001_15.geometry}
          material={materials['매테리얼.015']}
          skeleton={nodes.구체001_15.skeleton}
        />
        <skinnedMesh
          geometry={nodes.구체001_16.geometry}
          material={materials['매테리얼.018']}
          skeleton={nodes.구체001_16.skeleton}
        />
        <skinnedMesh
          geometry={nodes.구체001_17.geometry}
          material={materials['______________.001']}
          skeleton={nodes.구체001_17.skeleton}
        />
        <skinnedMesh
          geometry={nodes.구체001_18.geometry}
          material={materials['Suit.001']}
          skeleton={nodes.구체001_18.skeleton}
        />
        <skinnedMesh
          geometry={nodes.구체001_19.geometry}
          material={materials['wire_135059008.001']}
          skeleton={nodes.구체001_19.skeleton}
        />
        <skinnedMesh
          geometry={nodes.구체001_20.geometry}
          material={materials['매테리얼.010']}
          skeleton={nodes.구체001_20.skeleton}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/Sori_ani.glb')
